spring:
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret:
    access: pmAwd5izmqEULionmIAPrA==
    refresh: lKwppuqF4a+agwP0TIUo
